services:
  api:
    build: .
    container_name: nano-banana-api
    environment:
      - DEFAULT_MODEL=${DEFAULT_MODEL:-gemini-2.5-flash-image-preview}
      - DB_PATH=/data/app.db
      - GENAI_MAX_CONCURRENT=${GENAI_MAX_CONCURRENT:-1}
      - GENAI_MIN_INTERVAL_MS=${GENAI_MIN_INTERVAL_MS:-500}
      - GENAI_MAX_RETRIES=${GENAI_MAX_RETRIES:-3}
      - GENAI_BACKOFF_MS=${GENAI_BACKOFF_MS:-500}
      - GENAI_FORCE_SINGLE_ON_RETRY=${GENAI_FORCE_SINGLE_ON_RETRY:-1}
    ports:
      - "4041:8000"  # 在 NAS 上使用 4041 作为外部端口
    volumes:
      - data:/data
    restart: unless-stopped

volumes:
  data: