services:
  - type: web
    name: nano-banana-api
    env: docker
    autoDeploy: true
    plan: free
    region: oregon
    runtime: docker
    healthCheckPath: /healthz
    # Persistent disk for SQLite database
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: DB_PATH
        value: /data/app.db
      # When serving /public directly from FastAPI, CORS often isn't required.
      # If you need cross-origin calls, set your Streamlit domain via ALLOWED_ORIGINS in dashboard.